export enum AppRoutesEnums {
    MAIN = '/',
    ABOUT = 'about',
    PROFILE = 'profile',
    WORK_EDIT = 'work_edit',
    WORK_DETAILS = 'work_details',
    WORK_LIST = 'work_list',
    REVIEW_LIST = 'review_list',
    REVIEW_DETAILS = 'review_details',
    REVIEW_CREATE = 'review_create',
    REVIEW_EDIT = 'review_edit',
    ADMIN_DASHBOARD = 'admin_dashboard',
    SUCCESS_AUTH_PROVIDER = 'success_auth_provider',
    FORBIDDEN = 'forbidden',
    NOT_FOUND = 'not_found',
}
